"""Run the deterministic M08.4 Code RAG benchmark."""

from __future__ import annotations

import json
import time
from pathlib import Path

from rag_practice.code_rag import PythonRepositoryIndex
from rag_practice.evaluation.code_rag import evaluate_code_rankings


ROOT = Path(__file__).resolve().parents[3]
BENCHMARK = ROOT / "benchmarks" / "m08_code"
RESULTS = Path(__file__).resolve().parent / "results"


def load_queries() -> list[dict[str, object]]:
    return [
        json.loads(line)
        for line in (BENCHMARK / "queries.jsonl").read_text().splitlines()
        if line.strip()
    ]


def timed_rankings(
    index: PythonRepositoryIndex,
    queries: list[dict[str, object]],
    *,
    mode: str,
) -> tuple[dict[str, list[str]], dict[str, float]]:
    rankings: dict[str, list[str]] = {}
    latencies: dict[str, float] = {}
    for query in queries:
        query_id = str(query["id"])
        text = str(query["query"])
        started = time.perf_counter()
        if mode == "file_bm25":
            ranking = index.search_files(text, k=4)
        elif mode == "symbol_bm25":
            ranking = index.search_symbols(text, k=4)
        elif mode == "symbol_graph":
            ranking = index.search_symbol_graph(text, k=4)
        else:
            raise ValueError(mode)
        latencies[query_id] = (time.perf_counter() - started) * 1000.0
        rankings[query_id] = [item_id for item_id, _ in ranking]
    return rankings, latencies


def to_markdown(result: dict[str, object]) -> str:
    systems = result["systems"]
    lines = [
        "# M08.4 Code RAG results",
        "",
        (
            f"Benchmark: {result['benchmark']['files']} files, "
            f"{result['benchmark']['symbols']} AST symbols, "
            f"{result['benchmark']['queries']} queries."
        ),
        "",
        "| System | Recall@4 | Complete@4 | Primary Hit@1 | Single-answer location | Dependency complete | Call-site confusion | Context chars@4 | Exact line locators |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name in ("file_bm25", "symbol_bm25", "symbol_graph"):
        metrics = systems[name]["metrics"]
        lines.append(
            "| "
            + name
            + " | "
            + " | ".join(
                [
                    f"{metrics['recall@4']:.3f}",
                    f"{metrics['evidence_complete@4']:.3f}",
                    f"{metrics['primary_hit@1']:.3f}",
                    f"{metrics['single_evidence_answer_location_exact']:.3f}",
                    f"{metrics['dependency_complete@4']:.3f}",
                    f"{metrics['callsite_confusion_rate']:.3f}",
                    f"{metrics['mean_context_chars@4']:.1f}",
                    f"{metrics['exact_line_locators_available']:.3f}",
                ]
            )
            + " |"
        )

    lines += [
        "",
        "## Interpretation guardrails",
        "",
        "- File BM25 uses coarse files, so file-level recall can be high while the exact implementation/call-site distinction remains unresolved.",
        "- Symbol BM25 changes the retrieval unit but does not add graph expansion; symbol chunking alone can lose dependency evidence.",
        "- Symbol+graph adds explicit identifier routing plus outgoing/reverse call edges; it does not claim semantic program analysis.",
        "- Exact `code://...#Lx-Ly` locators are derived from Python AST spans, not generated by an LLM.",
        "- This tiny Python repository is a deterministic mechanism benchmark, not a RepoBench-scale or multilingual Code RAG claim.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    queries = load_queries()
    started = time.perf_counter()
    index = PythonRepositoryIndex(BENCHMARK / "repo")
    build_ms = (time.perf_counter() - started) * 1000.0

    systems: dict[str, object] = {}
    for mode in ("file_bm25", "symbol_bm25", "symbol_graph"):
        rankings, latencies = timed_rankings(index, queries, mode=mode)
        systems[mode] = evaluate_code_rankings(
            index,
            queries,
            system=mode,
            rankings=rankings,
            latencies_ms=latencies,
            k=4,
        )

    result = {
        "hypothesis": (
            "repository code retrieval needs structure-aware units and dependency context: "
            "coarse file retrieval can hit the right file yet confuse implementations with "
            "call sites, while symbol-only retrieval can miss cross-file dependency evidence"
        ),
        "benchmark": {
            "files": len(index.files),
            "symbols": len(index.symbols),
            "queries": len(queries),
            "call_edges": sum(len(edges) for edges in index.call_graph.values()),
        },
        "systems": systems,
        "system": {
            "index_build_ms": build_ms,
            "file_units": len(index.files),
            "symbol_units": len(index.symbols),
        },
        "graph": {
            symbol_id: targets
            for symbol_id, targets in index.call_graph.items()
            if targets
        },
    }

    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / "results.json").write_text(json.dumps(result, indent=2) + "\n")
    markdown = to_markdown(result)
    (RESULTS / "results.md").write_text(markdown)
    print(markdown)


if __name__ == "__main__":
    main()
